# Generated by Django 5.1.1 on 2025-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_laon_approve_transaction_loan_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawl'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Fund Transfer')], null=True),
        ),
    ]
