# Generated by Django 5.1.1 on 2025-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_bankrupt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
